CREATE TABLE IF NOT EXISTS tax_authority_codebooks (
    id serial PRIMARY KEY,
    title VARCHAR ( 255 ) NOT NULL,
    code TEXT NOT NULL,
    active BOOLEAN default true,
    tax_percentage FLOAT,
    tax_supplier_id INTEGER,
    release_percentage FLOAT,
    pio_percentage FLOAT,
    pio_supplier_id INTEGER,
    pio_percentage_employer_percentage FLOAT,
    pio_employer_supplier_id INTEGER,
    pio_percentage_employee_percentage FLOAT,
    pio_employee_supplier_id INTEGER,
    unemployment_percentage FLOAT,
    unemployment_supplier_id INTEGER,
    unemployment_employer_percentage FLOAT,
    unemployment_employer_supplier_id INTEGER,
    unemployment_employee_percentage FLOAT,
    unemployment_employee_supplier_id INTEGER,
    labor_fund FLOAT,
    labor_fund_supplier_id INTEGER,
    previous_income_percentage_less_than_700 FLOAT,
    previous_income_percentage_less_than_1000 FLOAT,
    previous_income_percentage_more_than_1000 FLOAT,
    coefficient FLOAT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
