INSERT INTO programs (parent_id, title, description, code, created_at, updated_at) VALUES
(NULL, 'Rad sudova', 'Rad sudova', 'RS', NOW(), NOW()),
(1, 'Nadleznost Osnovnih sudova', 'Nadleznost Osnovnih sudova', 'NOS', NOW(), NOW()),
(1, 'Rad Visih sudova', 'Rad Visih sudova', '12 003 007', NOW(), NOW()),
(1, 'Nadleznost Vrhovnog i apelacionog suda', 'Nadleznost Vrhovnog i apelacionog suda', '12 003 004', NOW(), NOW());

INSERT INTO activities (title, description, code, created_at, updated_at, organization_unit_id, sub_program_id) VALUES
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 1, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 2, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 3, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 4, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 5, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 6, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 7, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 8, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 9, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 10, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 11, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 12, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 13, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 14, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 15, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 16, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 17, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 18, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 19, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 20, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 21, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 22, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 23, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 24, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 25, 2),
('Vodjenje sudskih postupaka u ...', 'description', 'code', NOW(), NOW(), 26, 2);
